const ramos = [
  {
    id: "alg-trig",
    nombre: "Álgebra y Trigonometría",
    creditos: 6,
    desbloquea: ["alg-lineal"],
  },
  {
    id: "calc-dif",
    nombre: "Cálculo Diferencial",
    creditos: 6,
    desbloquea: ["calc-int", "electromagnetismo"],
  },
  {
    id: "quimica",
    nombre: "Química General",
    creditos: 8,
    desbloquea: [],
    color: "verde",
  },
  {
    id: "intro-ing",
    nombre: "Introducción a la Ing. Industrial",
    creditos: 6,
    desbloquea: ["software"],
  },
  {
    id: "form-int-1",
    nombre: "Formación Integral I",
    creditos: 2,
    desbloquea: [],
  },
  {
    id: "form-int-2",
    nombre: "Formación Integral II",
    creditos: 2,
    desbloquea: [],
  },
  {
    id: "alg-lineal",
    nombre: "Álgebra Lineal",
    creditos: 6,
    prereq: ["alg-trig"],
    desbloquea: ["ec-dif"],
  },
  {
    id: "calc-int",
    nombre: "Cálculo Integral",
    creditos: 6,
    prereq: ["calc-dif"],
    desbloquea: ["calc-multiv", "estadistica", "ec-dif"],
  },
  {
    id: "fis-mec",
    nombre: "Física Mecánica",
    creditos: 8,
    desbloquea: [],
  },
  {
    id: "software",
    nombre: "Software para la Ing. Industrial",
    creditos: 4,
    prereq: ["intro-ing"],
    desbloquea: ["algoritmos"],
  },
  {
    id: "emprendimiento",
    nombre: "Taller de Emprendimiento",
    creditos: 4,
    desbloquea: ["taller-basicas", "teoria-sistemas"],
  },
  {
    id: "algoritmos",
    nombre: "Algoritmos y Programación",
    creditos: 4,
    prereq: ["software"],
    desbloquea: [],
  },
  {
    id: "electromagnetismo",
    nombre: "Electromagnetismo",
    creditos: 8,
    prereq: ["calc-dif"],
    desbloquea: ["electrotecnia"],
  },
  {
    id: "estadistica",
    nombre: "Estadística",
    creditos: 6,
    prereq: ["calc-int"],
    desbloquea: ["metodos-prod", "inferencia"],
  },
  {
    id: "calc-multiv",
    nombre: "Cálculo Multivariable",
    creditos: 6,
    prereq: ["calc-int"],
    desbloquea: [],
  },
  {
    id: "ec-dif",
    nombre: "Ecuaciones Diferenciales",
    creditos: 6,
    prereq: ["alg-lineal", "calc-int"],
    desbloquea: [],
  },
  {
    id: "teoria-sistemas",
    nombre: "Teoría de Sistemas",
    creditos: 3,
    prereq: ["emprendimiento"],
    desbloquea: ["gestion-estrategica", "modelamiento"],
  },
  {
    id: "taller-basicas",
    nombre: "Taller de Ciencias Básicas",
    creditos: 3,
    prereq_creditos: 70,
    prereq: ["emprendimiento"],
    desbloquea: ["taller-ingenieria"],
  },
  {
    id: "taller-ingenieria",
    nombre: "Taller de Ciencias de la Ingeniería",
    creditos: 4,
    prereq_creditos: 100,
    prereq: ["taller-basicas"],
    desbloquea: ["taller-productivos"],
  },
  // Agrega más ramos aquí siguiendo la estructura
];
